### ISSUE TITLE
Experiencing SegmentStore CrashLoopBackOff due to OutOfMemoryError 

### ISSUE THREAD

**Issue by sumit-bm** [pravega/pravega#3564]
With moderate IO, small transaction IO and pravega-benchmark with 5 streams (10 writter, 10 reader with 1000 Byte size, 100 events per sec and 10 segments) experiencing segmentstores are  
going into `CrashLoopBackOff` with following exception after ~1day of IO operations.

```
java.lang.OutOfMemoryError: GC overhead limit exceeded
Dumping heap to java_pid1.hprof ...
Heap dump file created [2640783672 bytes in 8.774 secs]
Aborting due to java.lang.OutOfMemoryError: GC overhead limit exceeded
```
Environment details: PKS / K8 with medium cluster:
```
3 master nodes @ large.cpu (4 CPU, 4 GB Ram, 16 GB Disk)
5 worker nodes @ xlarge.cpu(8 cpu, 8 GB Ram, 32 GB Disk)
Tier-1 storage is from VSAN datastore
Tier-2 storage curved on NFS Client provisioner using Isilon as backend

Pravega version: zk-closed-client-issue-0.5.0-2162.0bbfa42
Zookeeper Operator : 0.2.1
Pravega Operator: 0.3.2
```
```
NAMESPACE           NAME                                             READY     STATUS             RESTARTS   AGE
default             isilon-nfs-client-provisioner-67b7ffff86-vn6z6   1/1       Running            0          1d
default             pravega-benchmark                                1/1       Running            0          2d
default             pravega-bookie-0                                 1/1       Running            1          1d
default             pravega-bookie-1                                 1/1       Running            1          2d
default             pravega-bookie-2                                 1/1       Running            1          1d
default             pravega-bookie-3                                 1/1       Running            1          2d
default             pravega-bookie-4                                 1/1       Running            1          1d
default             pravega-operator-779879b48-hbcnw                 1/1       Running            0          2d
default             pravega-pravega-controller-c67d6b758-hdpp9       1/1       Running            1          1d
default             pravega-pravega-controller-c67d6b758-l9stc       1/1       Running            2          2d
default             pravega-pravega-segmentstore-0                   1/1       Running            67         2d
default             pravega-pravega-segmentstore-1                   0/1       CrashLoopBackOff   125        2d
default             pravega-pravega-segmentstore-2                   1/1       Running            130        2d
default             pravega-zk-0                                     1/1       Running            0          2d
default             pravega-zk-1                                     1/1       Running            0          3h
default             pravega-zk-2                                     1/1       Running            0          2d
default             zookeeper-operator-685bfcbbc5-rk5cs              1/1       Running            0          2d
```

**Comment by RaulGracia** [comment]
@sumit-bm, could you describe the resources and JVM options you used for this experiment?

**Comment by sumit-bm** [comment]
@RaulGracia, this is same deployment what we discussed with all resources profile:
```
# cat pravega_resources.yaml 
apiVersion: "pravega.pravega.io/v1alpha1"
kind: "PravegaCluster"
metadata:
  name: "pravega"
spec:
  zookeeperUri: pravega-zk-client:2181

  bookkeeper:
    image:
      repository: devops-repo.isus.emc.com:8116/nautilus/bookkeeper
      tag: zk-closed-client-issue-0.5.0-2162.0bbfa42
      pullPolicy: IfNotPresent

    replicas: 4
    resources:
      requests:
        memory: "2Gi"
        cpu: "1000m"
      limits:
        memory: "4Gi"
        cpu: "2000m"

    storage:
      ledgerVolumeClaimTemplate:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: "standard"
        resources:
          requests:
            storage: 100Gi

      journalVolumeClaimTemplate:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: "standard"
        resources:
          requests:
            storage: 100Gi

      indexVolumeClaimTemplate:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: "standard"
        resources:
          requests:
            storage: 10Gi

    autoRecovery: true
    options:
      useHostNameAsBookieID: "true"

  pravega:
    controllerReplicas: 2
    controllerResources:
      requests:
        memory: "2Gi"
        cpu: "1000m"
      limits:
        memory: "3Gi"
        cpu: "2000m"

    segmentStoreReplicas: 3
    segmentStoreResources:
      requests:
        memory: "4Gi"
        cpu: "2000m"
      limits:
        memory: "6Gi"
        cpu: "4000m"

    cacheVolumeClaimTemplate:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "standard"
      resources:
        requests:
          storage: 30Gi

    image:
      repository: devops-repo.isus.emc.com:8116/nautilus/pravega
      tag: zk-closed-client-issue-0.5.0-2162.0bbfa42
      pullPolicy: IfNotPresent

    options:
      pravegaservice.cacheMaxSize: "21474836480"
      pravegaservice.writeBufferSizeMB: "512"
      pravegaservice.readCacheSizeMB: "4096"
      writer.flushThresholdBytes: "67108864"
      writer.flushThresholdMillis: "2000"
      writer.maxFlushSizeBytes: "67108864"
      writer.minReadTimeoutMillis: "200"
      hdfs.blockSize: "67108864"
      pravegaservice.containerCount: "32"
      controller.containerCount: "32"
      pravegaservice.threadPoolSize: "30"
      controller.retention.bucketCount: "10"
      controller.service.asyncTaskPoolSize: "20"
      controller.retention.threadCount: "4"

    tier2:
      filesystem:
        persistentVolumeClaim:
          claimName: pravega-tier2
```
```
cat zk_resource.yaml 
apiVersion: "zookeeper.pravega.io/v1beta1"
kind: "ZookeeperCluster"
metadata:
  name: "pravega-zk"
spec:
  size: 3
  pod:
    resources:
      requests:
        memory: "1Gi"
        cpu: "500m"
      limits:
        memory: "2Gi"
        cpu: "1000m" 
  persistence:
    accessModes: [ "ReadWriteOnce" ]
    storageClassName: "standard"
    resources:
      requests:
        storage: 100Gi
```
