### ISSUE TITLE
Review updating hdfs docker image

### ISSUE THREAD

**Issue by mejodev1** [pravega/pravega#3838]
Default hdfs docker image version used for Pravega is "2.7.7". There are a huge number of bug fixes and improvements available in the newer(2.8.x, 2.9.x. 3.x) releases,
Please refer https://hadoop.apache.org/releases.html
We need to review the hdfs docker images for Pravega also.

**Comment by fpj** [comment]
Thanks for reporting the issue, @mejodev1 , but why is this issue being open against the pravega queue? we do not produce hdfs images in this code base, do we?

**Comment by mejodev1** [comment]
We may need to update the hdfs version documented in the below file based on review:

[root@manager1 pravega]# cat docker/compose/swarm/hdfs.yml
#
# Copyright (c) 2017 Dell Inc., or its subsidiaries. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
version: '3'
services:
  hdfs:
    image: pravega/hdfs:2.7.7
    environment:
      HDFS_HOST: hdfs
[root@manager1 pravega]#

**Comment by mejodev1** [comment]
```
[root@manager1 pravega]# cat docker/compose/docker-compose.yml
#
# Copyright (c) 2017 Dell Inc., or its subsidiaries. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
version: '2'
services:
  zookeeper:
    image: zookeeper:3.5.4-beta
    ports:
      - "2181:2181"

  hdfs:
    image: pravega/hdfs:2.7.7
    ports:
      - "2222:2222"
      - "8020:8020"
      - "50090:50090"
      - "50010:50010"
      - "50020:50020"
      - "50075:50075"
      - "50070:50070"
    environment:
      SSH_PORT: 2222
      HDFS_HOST: ${HOST_IP}

.
.
.
```
