### ISSUE TITLE
Verify: Issue #3077: IO Failure observed as controller re-spawned

### ISSUE THREAD

**Issue by sumit-bm** [pravega/pravega#3905]
Verify issue #3077 IO failure on moderate IO on a docker swarm environment with the recent build

**Comment by RaulGracia** [comment]
Please, reproduce the experiment using the following `yml` for deploying Zookeeper, as it contains the changes from PR https://github.com/pravega/zookeeper-operator/pull/67:
```
apiVersion: "zookeeper.pravega.io/v1beta1"
kind: "ZookeeperCluster"
metadata:
  name: "zookeeper"
spec:
  image:
    repository: "tristan1900/zookeeper"
    tag: "0.2"
    pullPolicy: Always
  size: 3
```
