### ISSUE TITLE
On PKS, controller pod was not able to load config properly

### ISSUE THREAD

**Issue by kevinhan88** [pravega/pravega#3925]
**Problem description**
This is the finding of troubleshooting of issue #3692. When deployed on PKS or other K8S env, controller pod seems didn't load config file properly, instead it uses default config values.
This is at least true for metric config loading.

**Problem location**
Config, config.properties, and config folder

**Suggestions for an improvement**
Investigate the root cause of the issue and find the solution so that controller and segmentstore are seeing consistent config.

**Comment by RaulGracia** [comment]
@kevinhan88 how did you configure the parameters for the Controller? For instance, the QA team is changing default parameters both in the Controller and Segment Store using the Pravega Operator manifest `yml` and it works:
```
options:
      bookkeeper.bkWriteQuorumSize: "3"
      bookkeeper.bkAckQuorumSize: "2"
      pravegaservice.cacheMaxSize: "21474836480"
      pravegaservice.writeBufferSizeMB: "512"
      pravegaservice.readCacheSizeMB: "4096"
...
```
And, in the platform side, they make Pravega to publish metrics in the appropriate service, so setting the config for metrics is necessary there.

So, could you please add more information about how are you trying to change the Pravega config in PKS?
