### ISSUE TITLE
Segmentstore pod restarts with "OOMKilled" error while running high workload longevity

### ISSUE THREAD

**Issue by deenav** [pravega/pravega#4057]
**Problem description**
Observed `OOMKilled` for Segmenststore-1 pod after `19 hrs` of `mid-scale` longevity with `JDK11` client on Pravega build `0.5.0-2304.dfa3f9a`

Note:  Manifest for SS had been increased to have `8GB` max memory with log.level as `INFO` 

**kubectl describe output Error snip for SS-1**
```
  segmentstore
    State:          Running
      Started:      Wed, 24 Jul 2019 09:20:56 -0400
    Last State:     Terminated
      Reason:       OOMKilled
      Exit Code:    137
      Started:      Tue, 23 Jul 2019 14:12:40 -0400
      Finished:     Wed, 24 Jul 2019 09:20:55 -0400
```

**Environment details: PKS / K8 with medium cluster:**
```
3 master: xlarge: 4 CPU, 16 GB Ram, 32 GB Disk
10 worker: 2xlarge: 8 CPU, 32 GB Ram, 64 GB Disk
Tier-1 storage is from VSAN datastore
Tier-2 storage curved on NFS Client provisioner using Isilon as backend
```
```
Pravega version : 0.5.0-2304.dfa3f9a
Zookeeper Operator : pravega/zookeeper-operator:0.2.2
Pravega Operator: pravega/pravega-operator:0.3.3-rc1
```
**kubectl get po**
```
NAME                                                 READY   STATUS    RESTARTS   AGE
pravega-bookie-0                                     1/1     Running   4          19h
pravega-bookie-1                                     1/1     Running   0          19h
pravega-bookie-2                                     1/1     Running   0          19h
pravega-bookie-3                                     1/1     Running   0          19h
pravega-operator-78976dcb8c-rdgdj                    1/1     Running   0          19h
pravega-pravega-controller-6975979777-lz9x5          1/1     Running   0          19h
pravega-pravega-controller-6975979777-tgbgn          1/1     Running   0          19h
pravega-pravega-segmentstore-0                       1/1     Running   0          19h
pravega-pravega-segmentstore-1                       1/1     Running   1          19h
pravega-pravega-segmentstore-2                       1/1     Running   0          19h
pravega-zk-0                                         1/1     Running   0          20h
pravega-zk-1                                         1/1     Running   0          20h
pravega-zk-2                                         1/1     Running   0          20h
shaka-zulu-nfs-client-provisioner-5bcd87b9dc-44zsv   1/1     Running   0          20h
zookeeper-operator-747c796d9-d947l                   1/1     Running   0          20h
```

**Kubectl describe output for SS-1**
```
$ kubectl describe po/pravega-pravega-segmentstore-1
Name:               pravega-pravega-segmentstore-1
Namespace:          default
Priority:           0
PriorityClassName:  <none>
Node:               fe02b172-2a5e-4f2e-bd3a-f078659edde6/172.24.0.7
Start Time:         Tue, 23 Jul 2019 14:12:19 -0400
Labels:             app=pravega-cluster
                    component=pravega-segmentstore
                    controller-revision-hash=pravega-pravega-segmentstore-f6d94c495
                    pravega_cluster=pravega
                    statefulset.kubernetes.io/pod-name=pravega-pravega-segmentstore-1
Annotations:        <none>
Status:             Running
IP:                 172.28.0.15
Controlled By:      StatefulSet/pravega-pravega-segmentstore
Containers:
  pravega-segmentstore:
    Container ID:  docker://d279c85e635cbbfd6d1349eb130d6f0ca9680c027c6f65486c099a186a6cdc9d
    Image:         devops-repo.isus.emc.com:8116/nautilus/pravega:0.5.0-2304.dfa3f9a
    Image ID:      docker-pullable://devops-repo.isus.emc.com:8116/nautilus/pravega@sha256:e858e191a41e7f1263ccfd12db1c30d9394f581e04b81457a4df8f3ccb31902c
    Port:          12345/TCP
    Host Port:     0/TCP
    Args:
      segmentstore
    State:          Running
      Started:      Wed, 24 Jul 2019 09:20:56 -0400
    Last State:     Terminated
      Reason:       OOMKilled
      Exit Code:    137
      Started:      Tue, 23 Jul 2019 14:12:40 -0400
      Finished:     Wed, 24 Jul 2019 09:20:55 -0400
    Ready:          True
    Restart Count:  1
    Limits:
      cpu:     4
      memory:  8Gi
    Requests:
      cpu:      2
      memory:   4Gi
    Liveness:   exec [/bin/sh -c netstat -ltn 2> /dev/null | grep 12345 || ss -ltn 2> /dev/null | grep 12345] delay=300s timeout=1s period=15s #success=1 #failure=4
    Readiness:  exec [/bin/sh -c netstat -ltn 2> /dev/null | grep 12345 || ss -ltn 2> /dev/null | grep 12345] delay=0s timeout=1s period=10s #success=1 #failure=30
    Environment Variables from:
      pravega-pravega-segmentstore  ConfigMap  Optional: false
    Environment:
      POD_NAME:       pravega-pravega-segmentstore-1 (v1:metadata.name)
      POD_NAMESPACE:  default (v1:metadata.namespace)
    Mounts:
      /mnt/tier2 from tier2 (rw)
      /tmp/pravega/cache from cache (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-xgjcq (ro)
Conditions:
  Type              Status
  Initialized       True
  Ready             True
  ContainersReady   True
  PodScheduled      True
Volumes:
  cache:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  cache-pravega-pravega-segmentstore-1
    ReadOnly:   false
  tier2:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  pravega-tier2
    ReadOnly:   false
  default-token-xgjcq:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-xgjcq
    Optional:    false
QoS Class:       Burstable
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:          <none>
```

**Pravega manifest**
```
apiVersion: "pravega.pravega.io/v1alpha1"
kind: "PravegaCluster"
metadata:
  name: "pravega"
spec:
  zookeeperUri: "pravega-zk-0.pravega-zk-headless.default.svc.cluster.local:2181,pravega-zk-1.pravega-zk-headless.default.svc.cluster.local:2181,pravega-zk-2.pravega-zk-headless.default.svc.cluster.local:2181"

  bookkeeper:
    image:
      repository: devops-repo.isus.emc.com:8116/nautilus/bookkeeper
      tag: 0.5.0-2304.dfa3f9a
      pullPolicy: Always

    replicas: 4
    resources:
      requests:
        memory: "2Gi"
        cpu: "1000m"
      limits:
        memory: "6Gi"
        cpu: "2000m"

    storage:
      ledgerVolumeClaimTemplate:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: "standard"
        resources:
          requests:
            storage: 200Gi

      journalVolumeClaimTemplate:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: "standard"
        resources:
          requests:
            storage: 200Gi

      indexVolumeClaimTemplate:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: "standard"
        resources:
          requests:
            storage: 30Gi

    autoRecovery: true
    options:
      useHostNameAsBookieID: "true"
      minorCompactionThreshold: "0.4"
      minorCompactionInterval: "1800"
      majorCompactionThreshold: "0.8"
      majorCompactionInterval: "43200"
      isForceGCAllowWhenNoSpace: "true"
      diskUsageThreshold: "0.90"
      diskUsageWarnThreshold: "0.85"
      diskUsageLwmThreshold: "0.85"

  pravega:
    controllerReplicas: 2
    controllerResources:
      requests:
        memory: "2Gi"
        cpu: "1000m"
      limits:
        memory: "3Gi"
        cpu: "2000m"

    segmentStoreReplicas: 3
    segmentStoreResources:
      requests:
        memory: "4Gi"
        cpu: "2000m"
      limits:
        memory: "8Gi"
        cpu: "4000m"

    cacheVolumeClaimTemplate:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "standard"
      resources:
        requests:
          storage: 30Gi

    image:
      repository: devops-repo.isus.emc.com:8116/nautilus/pravega
      tag: 0.5.0-2304.dfa3f9a
      pullPolicy: Always

    options:
      bookkeeper.bkWriteQuorumSize: "3"
      bookkeeper.bkAckQuorumSize: "2"
      pravegaservice.cacheMaxSize: "3221225472"
      pravegaservice.cacheMaxTimeSeconds: "600"
      rocksdb.writeBufferSizeMB: "64"
      rocksdb.readCacheSizeMB: "8"
      writer.flushThresholdBytes: "67108864"
      writer.flushThresholdMillis: "2000"
      writer.maxFlushSizeBytes: "67108864"
      writer.minReadTimeoutMillis: "200"
      hdfs.blockSize: "67108864"
      pravegaservice.containerCount: "32"
      controller.containerCount: "32"
      pravegaservice.threadPoolSize: "30"
      controller.retention.bucketCount: "10"
      controller.service.asyncTaskPoolSize: "20"
      controller.retention.threadCount: "4"

    tier2:
      filesystem:
        persistentVolumeClaim:
          claimName: pravega-tier2
```
**kubectl top pods** output during SS pod restart
```
Wed Jul 24 08:56:52 EDT 2019
NAME                                                 CPU(cores)   MEMORY(bytes)
pravega-bookie-0                                     1850m        5000Mi
pravega-bookie-1                                     614m         3850Mi
pravega-bookie-2                                     373m         3767Mi
pravega-bookie-3                                     517m         3829Mi
pravega-operator-78976dcb8c-rdgdj                    5m           13Mi
pravega-pravega-controller-6975979777-lz9x5          24m          351Mi
pravega-pravega-controller-6975979777-tgbgn          20m          374Mi
pravega-pravega-segmentstore-0                       1587m        6773Mi
pravega-pravega-segmentstore-1                       2499m        7154Mi
pravega-pravega-segmentstore-2                       262m         6119Mi
pravega-zk-0                                         111m         107Mi
pravega-zk-1                                         60m          79Mi
pravega-zk-2                                         40m          80Mi
shaka-zulu-nfs-client-provisioner-5bcd87b9dc-44zsv   2m           9Mi
zookeeper-operator-747c796d9-d947l                   6m           13Mi
Wed Jul 24 08:58:56 EDT 2019
NAME                                                 CPU(cores)   MEMORY(bytes)
pravega-bookie-0                                     1925m        3694Mi
pravega-bookie-1                                     385m         3947Mi
pravega-bookie-2                                     404m         3940Mi
pravega-bookie-3                                     393m         3703Mi
pravega-operator-78976dcb8c-rdgdj                    6m           13Mi
pravega-pravega-controller-6975979777-lz9x5          30m          353Mi
pravega-pravega-controller-6975979777-tgbgn          23m          375Mi
pravega-pravega-segmentstore-0                       1523m        6935Mi
pravega-pravega-segmentstore-2                       203m         6507Mi
pravega-zk-0                                         66m          86Mi
pravega-zk-1                                         58m          79Mi
pravega-zk-2                                         63m          102Mi
shaka-zulu-nfs-client-provisioner-5bcd87b9dc-44zsv   2m           9Mi
zookeeper-operator-747c796d9-d947l                   6m           13Mi
Wed Jul 24 09:00:59 EDT 2019
NAME                                                 CPU(cores)   MEMORY(bytes)
pravega-bookie-0                                     336m         3659Mi
pravega-bookie-1                                     619m         3951Mi
pravega-bookie-2                                     626m         3779Mi
pravega-bookie-3                                     499m         3999Mi
pravega-operator-78976dcb8c-rdgdj                    6m           13Mi
pravega-pravega-controller-6975979777-lz9x5          22m          353Mi
pravega-pravega-controller-6975979777-tgbgn          17m          374Mi
pravega-pravega-segmentstore-0                       1593m        6892Mi
pravega-pravega-segmentstore-1                       2m           6Mi
pravega-pravega-segmentstore-2                       2562m        6652Mi
pravega-zk-0                                         43m          86Mi
pravega-zk-1                                         41m          100Mi
pravega-zk-2                                         49m          80Mi
```

Attaching Segmentstore-1 pod's previous (restart) log [pravega-pravega-segmentstore-1-prev.zip](https://github.com/pravega/pravega/files/3430148/pravega-pravega-segmentstore-1-prev.zip)

`kubectl top pods` data for complete test run [kubectl_top_pods.log](https://github.com/pravega/pravega/files/3430238/kubectl_top_pods.log)

**Comment by deenav** [comment]
This issue gets reproduced while running `mid-scale` longevity with `JDK11` client on Pravega `0.5.0-rc1` release build as well.

**Comment by RaulGracia** [comment]
After debugging and measuring multiple runs, we observed that the problem is likely configuring Bookkeeper `writeQuorum=3` and `ackQuorum=2`. The reason is that under a high workload, if a Bookie is slower than the other 2 (e.g., paused by data compaction), we keep writing data and accumulating buffers in memory waiting for the slow bookie to ack, which may make the Segment Store to run out of memory. Now I'm executing 2 longevity workloads with  `writeQuorum=ackQuorum=3` (one in AWS, one in a Beta Rack), and we have not seen any restart for +1 day/+12 hours, respectively.

**Comment by RaulGracia** [comment]
After investigating this issue, it looks like that the main factor for observing this OOM errors is the fact of configuring `ackQuorum < writeQuorum` in the Pravega manifest. The reason is that, if a Bookie is slower for some time (e.g., it is executing data compaction), the Segment Store will continue writing data to it, as it won't wait for the ACKs for this Bookie. This could manifest either in OOM errors in the Segment Store or Bookie sides.

As a proof that this setting `ackQuorum = writeQuorum` fixes the issue, here there are 3 longevity experiments running without any king of restart:

1) On-premise cluster, `mid-scale` workload, 1 SSS / 3 Bookies:
```
λ kubectl.exe get pods
NAME                                                        READY   STATUS    RESTARTS   AGE
grafana-766bf7d564-qkbrx                                    1/1     Running   0          2d21h
influxdb-698d798588-z4kcs                                   1/1     Running   0          2d21h
pravega-bookie-0                                            1/1     Running   0          2d7h
pravega-bookie-1                                            1/1     Running   0          2d7h
pravega-bookie-2                                            1/1     Running   0          2d7h
pravega-operator-684b6c7f96-ffmlw                           1/1     Running   0          2d21h
pravega-pravega-controller-6cf75d99c6-5v7tc                 1/1     Running   0          2d7h
pravega-pravega-segmentstore-0                              1/1     Running   0          2d7h
quarrelsome-zorse-nfs-client-provisioner-6c77ddd878-phx6m   1/1     Running   0          2d7h
zookeeper-0                                                 1/1     Running   0          2d7h
zookeeper-1                                                 1/1     Running   0          2d7h
zookeeper-2                                                 1/1     Running   0          2d7h
zookeeper-operator-5bb86b8d59-rvj46                         1/1     Running   0          2d21h
```

2) On-premise cluster, `mid-scale` workload, 1 SSS / 3 Bookies:
```
λ kubectl.exe get pods
NAME                                                  READY   STATUS    RESTARTS   AGE
crusty-oyster-nfs-client-provisioner-dc5b7549-nndwc   1/1     Running   0          2d9h
grafana-766bf7d564-8jsnk                              1/1     Running   0          2d10h
influxdb-698d798588-slzn7                             1/1     Running   0          9d
pravega-bookie-0                                      1/1     Running   0          2d9h
pravega-bookie-1                                      1/1     Running   0          2d9h
pravega-bookie-2                                      1/1     Running   0          2d9h
pravega-operator-684b6c7f96-wx7zd                     1/1     Running   0          3d11h
pravega-pravega-controller-6cf75d99c6-72rrf           1/1     Running   0          2d9h
pravega-pravega-segmentstore-0                        1/1     Running   0          2d9h
zookeeper-0                                           1/1     Running   0          2d9h
zookeeper-1                                           1/1     Running   0          2d9h
zookeeper-2                                           1/1     Running   0          2d9h
zookeeper-operator-5bb86b8d59-gckvz                   1/1     Running   0          9d
```

3) AWS cluster, `mid-scale` workload, 1 SSS / 3 Bookies:
 ```
λ kubectl.exe get pods
NAME                                                   READY   STATUS    RESTARTS   AGE
grafana-766bf7d564-xtqtf                               1/1     Running   0          4d9h
influxdb-698d798588-q97wh                              1/1     Running   0          4d9h
pravega-bookie-0                                       1/1     Running   0          4d8h
pravega-bookie-1                                       1/1     Running   0          4d8h
pravega-bookie-2                                       1/1     Running   0          4d8h
pravega-operator-684b6c7f96-92wsl                      1/1     Running   0          4d9h
pravega-pravega-controller-6cf75d99c6-226gc            1/1     Running   0          4d8h
pravega-pravega-segmentstore-0                         1/1     Running   0          4d8h
pugnacious-clownfish-efs-provisioner-65f4f567f-2ph94   1/1     Running   0          4d9h
zookeeper-0                                            1/1     Running   0          4d9h
zookeeper-1                                            1/1     Running   0          4d9h
zookeeper-2                                            1/1     Running   0          4d9h
zookeeper-operator-5bb86b8d59-sg6km                    1/1     Running   0          4d9h
```

Note that in the rest of runs, we got Segment Store or Bookie restarts every few hours.

**Comment by deenav** [comment]
I have verified this issue by running `mid-scale` longevity with `ackQuorum = writeQuorum` manifest in PKS cluster and the test is running fine for more than `5+ days` without any `OOMKilled` error.

```
kubectl get po --all-namespaces
NAMESPACE           NAME                                                READY   STATUS      RESTARTS   AGE
default             grafana-766bf7d564-5jn27                            1/1     Running     0          5d18h
default             influxdb-698d798588-m22vj                           1/1     Running     0          5d18h
default             pravega-bookie-0                                    1/1     Running     0          5d18h
default             pravega-bookie-1                                    1/1     Running     0          5d18h
default             pravega-bookie-2                                    1/1     Running     0          5d18h
default             pravega-bookie-3                                    1/1     Running     0          5d18h
default             pravega-operator-78976dcb8c-ndrxd                   1/1     Running     0          5d18h
default             pravega-pravega-controller-54746b5ff6-l4qbb         1/1     Running     0          5d18h
default             pravega-pravega-controller-54746b5ff6-s54bm         1/1     Running     0          5d18h
default             pravega-pravega-segmentstore-0                      1/1     Running     0          5d18h
default             pravega-pravega-segmentstore-1                      1/1     Running     0          5d18h
default             pravega-pravega-segmentstore-2                      1/1     Running     0          5d18h
default             pravega-zk-0                                        1/1     Running     0          5d18h
default             pravega-zk-1                                        1/1     Running     0          5d18h
default             pravega-zk-2                                        1/1     Running     0          5d18h
default             shaka-zulu-nfs-client-provisioner-564775788-b2kx2   1/1     Running     0          5d19h
default             zookeeper-operator-747c796d9-jb8zl                  1/1     Running     0          5d19h
```
Pravega manifest used for the test:
```
apiVersion: "pravega.pravega.io/v1alpha1"
kind: "PravegaCluster"
metadata:
  name: "pravega"
spec:
  zookeeperUri: "pravega-zk-0.pravega-zk-headless.default.svc.cluster.local:2181,pravega-zk-1.pravega-zk-headless.default.svc.cluster.local:2181,pravega-zk-2.pravega-zk-headless.default.svc.cluster.local:2181"

  bookkeeper:
    image:
      repository: devops-repo.isus.emc.com:8116/nautilus/bookkeeper
      tag: 0.5.0-2306.a5a5cdf
      pullPolicy: Always

    replicas: 4
    resources:
      requests:
        memory: "2Gi"
        cpu: "1000m"
      limits:
        memory: "6Gi"
        cpu: "2000m"

    storage:
      ledgerVolumeClaimTemplate:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: "standard"
        resources:
          requests:
            storage: 200Gi

      journalVolumeClaimTemplate:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: "standard"
        resources:
          requests:
            storage: 200Gi

      indexVolumeClaimTemplate:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: "standard"
        resources:
          requests:
            storage: 30Gi

    autoRecovery: true
    options:
      useHostNameAsBookieID: "true"
      minorCompactionThreshold: "0.4"
      minorCompactionInterval: "1800"
      majorCompactionThreshold: "0.8"
      majorCompactionInterval: "43200"
      isForceGCAllowWhenNoSpace: "true"
      diskUsageThreshold: "0.90"
      diskUsageWarnThreshold: "0.85"
      diskUsageLwmThreshold: "0.85"

  pravega:
    controllerReplicas: 2
    controllerResources:
      requests:
        memory: "2Gi"
        cpu: "1000m"
      limits:
        memory: "3Gi"
        cpu: "2000m"

    segmentStoreReplicas: 3
    segmentStoreResources:
      requests:
        memory: "4Gi"
        cpu: "2000m"
      limits:
        memory: "8Gi"
        cpu: "4000m"

    cacheVolumeClaimTemplate:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "standard"
      resources:
        requests:
          storage: 30Gi

    image:
      repository: devops-repo.isus.emc.com:8116/nautilus/pravega
      tag: 0.5.0-2306.a5a5cdf
      pullPolicy: Always

    options:
      bookkeeper.bkWriteQuorumSize: "3"
      bookkeeper.bkAckQuorumSize: "3"
      pravegaservice.cacheMaxSize: "3221225472"
      pravegaservice.cacheMaxTimeSeconds: "600"
      rocksdb.writeBufferSizeMB: "64"
      rocksdb.readCacheSizeMB: "8"
      rocksdb.cacheBlockSizeKB: "32"
      writer.flushThresholdBytes: "67108864"
      writer.flushThresholdMillis: "2000"
      writer.maxFlushSizeBytes: "67108864"
      writer.minReadTimeoutMillis: "200"
      hdfs.blockSize: "67108864"
      pravegaservice.containerCount: "32"
      controller.containerCount: "32"
      pravegaservice.threadPoolSize: "30"
      controller.retention.bucketCount: "10"
      controller.service.asyncTaskPoolSize: "20"
      controller.retention.threadCount: "4"
      log.level: "INFO"
      metrics.dynamicCacheSize: "100000"
      metrics.enableStatistics: "true"
      metrics.enableStatsDReporter: "false"
      metrics.statsdHost: "telegraph.default"
      metrics.statsdPort: "8125"
      metrics.enableInfluxDBReporter: "true"
      metrics.outputFrequencySeconds: "10"
      metrics.influxDBURI: "http://172.28.139.2:8086"
      controller.metrics.dynamicCacheSize: "100000"
      controller.metrics.enableStatistics: "true"
      controller.metrics.enableStatsDReporter: "false"
      controller.metrics.statsdHost: "telegraph.default"
      controller.metrics.statsdPort: "8125"
      controller.metrics.enableInfluxDBReporter: "true"
      controller.metrics.outputFrequencySeconds: "10"
      controller.metrics.influxDBURI: "http://172.28.139.2:8086"

    tier2:
      filesystem:
        persistentVolumeClaim:
          claimName: pravega-tier2
```
