### ISSUE TITLE
Bookie pod restarts with "java.lang.OutOfMemoryError: Java heap space"  while running high workload longevity

### ISSUE THREAD

**Issue by deenav** [pravega/pravega#4058]
**Problem description**
Observed ` java.lang.OutOfMemoryError: Java heap space` for bookkeeper-0 pod after `15 hrs` of `mid-scale` longevity with `JDK11` client on Pravega build `0.5.0-2304.dfa3f9a`

Note: Manifest for Bookkeeper had been increased to have `6 GB` max memory with log.level as `INFO`

**OOM Error log of BK-0**
```
  2019-07-24 07:35:29,579 - INFO  - [SortedLedgerStorage-0:SortedLedgerStorage$1@211] - Started flushing mem table.
java.lang.OutOfMemoryError: Java heap space
Dumping heap to java_pid69.hprof ...
Heap dump file created [2940203562 bytes in 23.061 secs]
Aborting due to java.lang.OutOfMemoryError: Java heap space
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  Internal Error (debug.cpp:308), pid=69, tid=0x00007f44a66bd700
#  fatal error: OutOfMemory encountered: Java heap space
#
# JRE version: OpenJDK Runtime Environment (8.0_191-b12) (build 1.8.0_191-b12)
# Java VM: OpenJDK 64-Bit Server VM (25.191-b12 mixed mode linux-amd64 compressed oops)
# Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
#
# An error report file with more information is saved as:
# /opt/bookkeeper/hs_err_pid69.log
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
#
/opt/bookkeeper/scripts/entrypoint.sh: line 39:    68 Aborted                 sudo -s -E -u "$BK_USER" /bin/bash "$@"
```
Unfortunately java heap dump not generated for the Bookie OOM due to 
```
# Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
```

**Environment details: PKS / K8 with medium cluster:**
```
3 master: xlarge: 4 CPU, 16 GB Ram, 32 GB Disk
10 worker: 2xlarge: 8 CPU, 32 GB Ram, 64 GB Disk
Tier-1 storage is from VSAN datastore
Tier-2 storage curved on NFS Client provisioner using Isilon as backend
```
```
Pravega version : 0.5.0-2304.dfa3f9a
Zookeeper Operator : pravega/zookeeper-operator:0.2.2
Pravega Operator: pravega/pravega-operator:0.3.3-rc1
```

**kubectl get po**
```
NAMESPACE           NAME                                                 READY   STATUS      RESTARTS   AGE
default             pravega-bookie-0                                     1/1     Running     3          15h
default             pravega-bookie-1                                     1/1     Running     0          15h
default             pravega-bookie-2                                     1/1     Running     0          15h
default             pravega-bookie-3                                     1/1     Running     0          15h
default             pravega-operator-78976dcb8c-rdgdj                    1/1     Running     0          15h
default             pravega-pravega-controller-6975979777-lz9x5          1/1     Running     0          15h
default             pravega-pravega-controller-6975979777-tgbgn          1/1     Running     0          15h
default             pravega-pravega-segmentstore-0                       1/1     Running     0          15h
default             pravega-pravega-segmentstore-1                       1/1     Running     0          15h
default             pravega-pravega-segmentstore-2                       1/1     Running     0          15h
default             pravega-zk-0                                         1/1     Running     0          16h
default             pravega-zk-1                                         1/1     Running     0          16h
default             pravega-zk-2                                         1/1     Running     0          16h
```

**Pravega manifest**
```
apiVersion: "pravega.pravega.io/v1alpha1"
kind: "PravegaCluster"
metadata:
  name: "pravega"
spec:
  zookeeperUri: "pravega-zk-0.pravega-zk-headless.default.svc.cluster.local:2181,pravega-zk-1.pravega-zk-headless.default.svc.cluster.local:2181,pravega-zk-2.pravega-zk-headless.default.svc.cluster.local:2181"

  bookkeeper:
    image:
      repository: devops-repo.isus.emc.com:8116/nautilus/bookkeeper
      tag: 0.5.0-2304.dfa3f9a
      pullPolicy: Always

    replicas: 4
    resources:
      requests:
        memory: "2Gi"
        cpu: "1000m"
      limits:
        memory: "6Gi"
        cpu: "2000m"

    storage:
      ledgerVolumeClaimTemplate:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: "standard"
        resources:
          requests:
            storage: 200Gi

      journalVolumeClaimTemplate:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: "standard"
        resources:
          requests:
            storage: 200Gi

      indexVolumeClaimTemplate:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: "standard"
        resources:
          requests:
            storage: 30Gi

    autoRecovery: true
    options:
      useHostNameAsBookieID: "true"
      minorCompactionThreshold: "0.4"
      minorCompactionInterval: "1800"
      majorCompactionThreshold: "0.8"
      majorCompactionInterval: "43200"
      isForceGCAllowWhenNoSpace: "true"
      diskUsageThreshold: "0.90"
      diskUsageWarnThreshold: "0.85"
      diskUsageLwmThreshold: "0.85"

  pravega:
    controllerReplicas: 2
    controllerResources:
      requests:
        memory: "2Gi"
        cpu: "1000m"
      limits:
        memory: "3Gi"
        cpu: "2000m"

    segmentStoreReplicas: 3
    segmentStoreResources:
      requests:
        memory: "4Gi"
        cpu: "2000m"
      limits:
        memory: "8Gi"
        cpu: "4000m"

    cacheVolumeClaimTemplate:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "standard"
      resources:
        requests:
          storage: 30Gi

    image:
      repository: devops-repo.isus.emc.com:8116/nautilus/pravega
      tag: 0.5.0-2304.dfa3f9a
      pullPolicy: Always

    options:
      bookkeeper.bkWriteQuorumSize: "3"
      bookkeeper.bkAckQuorumSize: "2"
      pravegaservice.cacheMaxSize: "3221225472"
      pravegaservice.cacheMaxTimeSeconds: "600"
      rocksdb.writeBufferSizeMB: "64"
      rocksdb.readCacheSizeMB: "8"
      writer.flushThresholdBytes: "67108864"
      writer.flushThresholdMillis: "2000"
      writer.maxFlushSizeBytes: "67108864"
      writer.minReadTimeoutMillis: "200"
      hdfs.blockSize: "67108864"
      pravegaservice.containerCount: "32"
      controller.containerCount: "32"
      pravegaservice.threadPoolSize: "30"
      controller.retention.bucketCount: "10"
      controller.service.asyncTaskPoolSize: "20"
      controller.retention.threadCount: "4"

    tier2:
      filesystem:
        persistentVolumeClaim:
          claimName: pravega-tier2
```

Attaching Bookkeeper pod's previous (3rd restart) log [pravega-bookie-0-prev.log](https://github.com/pravega/pravega/files/3430334/pravega-bookie-0-prev.log)

`kubectl top pods` data for complete test run [kubectl_top_pods.log](https://github.com/pravega/pravega/files/3430339/kubectl_top_pods.log)

**Comment by deenav** [comment]
This issue gets reproduced while running mid-scale longevity with JDK11 client on Pravega 0.5.0-rc1 release build as well.

**Comment by RaulGracia** [comment]
After investigating this issue, it looks like that the main factor for observing this OOM errors is the fact of configuring `ackQuorum < writeQuorum` in the Pravega manifest. The reason is that, if a Bookie is slower for some time (e.g., it is executing data compaction), the Segment Store will continue writing data to it, as it won't wait for the ACKs for this Bookie. This could manifest either in OOM errors in the Segment Store or Bookie sides.

As a proof that this setting `ackQuorum = writeQuorum` fixes the issue, here there are 3 longevity experiments running without any king of restart:

1) On-premise cluster, `mid-scale` workload, 1 SSS / 3 Bookies:
```
λ kubectl.exe get pods
NAME                                                        READY   STATUS    RESTARTS   AGE
grafana-766bf7d564-qkbrx                                    1/1     Running   0          2d21h
influxdb-698d798588-z4kcs                                   1/1     Running   0          2d21h
pravega-bookie-0                                            1/1     Running   0          2d7h
pravega-bookie-1                                            1/1     Running   0          2d7h
pravega-bookie-2                                            1/1     Running   0          2d7h
pravega-operator-684b6c7f96-ffmlw                           1/1     Running   0          2d21h
pravega-pravega-controller-6cf75d99c6-5v7tc                 1/1     Running   0          2d7h
pravega-pravega-segmentstore-0                              1/1     Running   0          2d7h
quarrelsome-zorse-nfs-client-provisioner-6c77ddd878-phx6m   1/1     Running   0          2d7h
zookeeper-0                                                 1/1     Running   0          2d7h
zookeeper-1                                                 1/1     Running   0          2d7h
zookeeper-2                                                 1/1     Running   0          2d7h
zookeeper-operator-5bb86b8d59-rvj46                         1/1     Running   0          2d21h
```

2) On-premise cluster, `mid-scale` workload, 1 SSS / 3 Bookies:
```
λ kubectl.exe get pods
NAME                                                  READY   STATUS    RESTARTS   AGE
crusty-oyster-nfs-client-provisioner-dc5b7549-nndwc   1/1     Running   0          2d9h
grafana-766bf7d564-8jsnk                              1/1     Running   0          2d10h
influxdb-698d798588-slzn7                             1/1     Running   0          9d
pravega-bookie-0                                      1/1     Running   0          2d9h
pravega-bookie-1                                      1/1     Running   0          2d9h
pravega-bookie-2                                      1/1     Running   0          2d9h
pravega-operator-684b6c7f96-wx7zd                     1/1     Running   0          3d11h
pravega-pravega-controller-6cf75d99c6-72rrf           1/1     Running   0          2d9h
pravega-pravega-segmentstore-0                        1/1     Running   0          2d9h
zookeeper-0                                           1/1     Running   0          2d9h
zookeeper-1                                           1/1     Running   0          2d9h
zookeeper-2                                           1/1     Running   0          2d9h
zookeeper-operator-5bb86b8d59-gckvz                   1/1     Running   0          9d
```

3) AWS cluster, `mid-scale` workload, 1 SSS / 3 Bookies:
 ```
λ kubectl.exe get pods
NAME                                                   READY   STATUS    RESTARTS   AGE
grafana-766bf7d564-xtqtf                               1/1     Running   0          4d9h
influxdb-698d798588-q97wh                              1/1     Running   0          4d9h
pravega-bookie-0                                       1/1     Running   0          4d8h
pravega-bookie-1                                       1/1     Running   0          4d8h
pravega-bookie-2                                       1/1     Running   0          4d8h
pravega-operator-684b6c7f96-92wsl                      1/1     Running   0          4d9h
pravega-pravega-controller-6cf75d99c6-226gc            1/1     Running   0          4d8h
pravega-pravega-segmentstore-0                         1/1     Running   0          4d8h
pugnacious-clownfish-efs-provisioner-65f4f567f-2ph94   1/1     Running   0          4d9h
zookeeper-0                                            1/1     Running   0          4d9h
zookeeper-1                                            1/1     Running   0          4d9h
zookeeper-2                                            1/1     Running   0          4d9h
zookeeper-operator-5bb86b8d59-sg6km                    1/1     Running   0          4d9h
```

Note that in the rest of runs, we got Segment Store or Bookie restarts every few hours.

**Comment by deenav** [comment]
I have verified this issue by running `mid-scale` longevity with `ackQuorum = writeQuorum` manifest in PKS cluster and the test is running fine for more than `5+ days` without any `OOM` issue or `OOMKilled` error.

```
kubectl get po --all-namespaces
NAMESPACE           NAME                                                READY   STATUS      RESTARTS   AGE
default             grafana-766bf7d564-5jn27                            1/1     Running     0          5d18h
default             influxdb-698d798588-m22vj                           1/1     Running     0          5d18h
default             pravega-bookie-0                                    1/1     Running     0          5d18h
default             pravega-bookie-1                                    1/1     Running     0          5d18h
default             pravega-bookie-2                                    1/1     Running     0          5d18h
default             pravega-bookie-3                                    1/1     Running     0          5d18h
default             pravega-operator-78976dcb8c-ndrxd                   1/1     Running     0          5d18h
default             pravega-pravega-controller-54746b5ff6-l4qbb         1/1     Running     0          5d18h
default             pravega-pravega-controller-54746b5ff6-s54bm         1/1     Running     0          5d18h
default             pravega-pravega-segmentstore-0                      1/1     Running     0          5d18h
default             pravega-pravega-segmentstore-1                      1/1     Running     0          5d18h
default             pravega-pravega-segmentstore-2                      1/1     Running     0          5d18h
default             pravega-zk-0                                        1/1     Running     0          5d18h
default             pravega-zk-1                                        1/1     Running     0          5d18h
default             pravega-zk-2                                        1/1     Running     0          5d18h
default             shaka-zulu-nfs-client-provisioner-564775788-b2kx2   1/1     Running     0          5d19h
default             zookeeper-operator-747c796d9-jb8zl                  1/1     Running     0          5d19h
```
Pravega manifest used for the test:
```
apiVersion: "pravega.pravega.io/v1alpha1"
kind: "PravegaCluster"
metadata:
  name: "pravega"
spec:
  zookeeperUri: "pravega-zk-0.pravega-zk-headless.default.svc.cluster.local:2181,pravega-zk-1.pravega-zk-headless.default.svc.cluster.local:2181,pravega-zk-2.pravega-zk-headless.default.svc.cluster.local:2181"

  bookkeeper:
    image:
      repository: devops-repo.isus.emc.com:8116/nautilus/bookkeeper
      tag: 0.5.0-2306.a5a5cdf
      pullPolicy: Always

    replicas: 4
    resources:
      requests:
        memory: "2Gi"
        cpu: "1000m"
      limits:
        memory: "6Gi"
        cpu: "2000m"

    storage:
      ledgerVolumeClaimTemplate:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: "standard"
        resources:
          requests:
            storage: 200Gi

      journalVolumeClaimTemplate:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: "standard"
        resources:
          requests:
            storage: 200Gi

      indexVolumeClaimTemplate:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: "standard"
        resources:
          requests:
            storage: 30Gi

    autoRecovery: true
    options:
      useHostNameAsBookieID: "true"
      minorCompactionThreshold: "0.4"
      minorCompactionInterval: "1800"
      majorCompactionThreshold: "0.8"
      majorCompactionInterval: "43200"
      isForceGCAllowWhenNoSpace: "true"
      diskUsageThreshold: "0.90"
      diskUsageWarnThreshold: "0.85"
      diskUsageLwmThreshold: "0.85"

  pravega:
    controllerReplicas: 2
    controllerResources:
      requests:
        memory: "2Gi"
        cpu: "1000m"
      limits:
        memory: "3Gi"
        cpu: "2000m"

    segmentStoreReplicas: 3
    segmentStoreResources:
      requests:
        memory: "4Gi"
        cpu: "2000m"
      limits:
        memory: "8Gi"
        cpu: "4000m"

    cacheVolumeClaimTemplate:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "standard"
      resources:
        requests:
          storage: 30Gi

    image:
      repository: devops-repo.isus.emc.com:8116/nautilus/pravega
      tag: 0.5.0-2306.a5a5cdf
      pullPolicy: Always

    options:
      bookkeeper.bkWriteQuorumSize: "3"
      bookkeeper.bkAckQuorumSize: "3"
      pravegaservice.cacheMaxSize: "3221225472"
      pravegaservice.cacheMaxTimeSeconds: "600"
      rocksdb.writeBufferSizeMB: "64"
      rocksdb.readCacheSizeMB: "8"
      rocksdb.cacheBlockSizeKB: "32"
      writer.flushThresholdBytes: "67108864"
      writer.flushThresholdMillis: "2000"
      writer.maxFlushSizeBytes: "67108864"
      writer.minReadTimeoutMillis: "200"
      hdfs.blockSize: "67108864"
      pravegaservice.containerCount: "32"
      controller.containerCount: "32"
      pravegaservice.threadPoolSize: "30"
      controller.retention.bucketCount: "10"
      controller.service.asyncTaskPoolSize: "20"
      controller.retention.threadCount: "4"
      log.level: "INFO"
      metrics.dynamicCacheSize: "100000"
      metrics.enableStatistics: "true"
      metrics.enableStatsDReporter: "false"
      metrics.statsdHost: "telegraph.default"
      metrics.statsdPort: "8125"
      metrics.enableInfluxDBReporter: "true"
      metrics.outputFrequencySeconds: "10"
      metrics.influxDBURI: "http://172.28.139.2:8086"
      controller.metrics.dynamicCacheSize: "100000"
      controller.metrics.enableStatistics: "true"
      controller.metrics.enableStatsDReporter: "false"
      controller.metrics.statsdHost: "telegraph.default"
      controller.metrics.statsdPort: "8125"
      controller.metrics.enableInfluxDBReporter: "true"
      controller.metrics.outputFrequencySeconds: "10"
      controller.metrics.influxDBURI: "http://172.28.139.2:8086"

    tier2:
      filesystem:
        persistentVolumeClaim:
          claimName: pravega-tier2
```
