### ISSUE TITLE
Segment Store doesn't expose metrics with legacy property names.

### ISSUE THREAD

**Issue by AndreyKoltsov1997** [pravega/pravega#4875]
**Problem description**
I've used Pravega docker image built from  https://github.com/pravega/pravega/commit/3a0164c0bf584d637f73aeb9991c82cb7fc348f6 while I was deploying Pravega on Kubernetes cluster. This manifest A / B I've used could be found below.
Using **Manifest A** (legacy property names), I was able to get only Controller's metrics in my Influx DB while Segment Store haven't sent them. With **Manifest B** (new property names), I was able to get metrics for both.
Note that I haven't observed any metrics-related errors in Segment Store's logs.
According to [MetricsConfig class](https://github.com/pravega/pravega/blob/master/shared/metrics/src/main/java/io/pravega/shared/metrics/MetricsConfig.java#L23), I assume Pravega should support backward compatibility for the legacy property names. 

**Manifests**
`<InfluxDB target DB name>` - name of DB inside my Influx DB instance;
`<INFLUX DB URI>` - URI of my InfluxDB;

- **1. Manifest A: legacy metrics' property names, Segment Store doesn't expose metrics**
```
apiVersion: "pravega.pravega.io/v1beta1"
kind: "PravegaCluster"
metadata:
  name: "pravega-cluster"
spec:
  version: "0.8.0-2568.efa9e08b2"
  zookeeperUri: zookeeper-client:2181
  bookkeeperUri: "bookkeeper-bookie-0.bookkeeper-bookie-headless.default.svc.cluster.local:3181"

  pravega:
    controllerReplicas: 1
    controllerResources:
      requests:
        memory: "3Gi"
        cpu: "500m"
      limits:
        memory: "5Gi"
        cpu: "3000m"

    segmentStoreReplicas: 1
    segmentStoreResources:
      requests:
        memory: "4Gi"
        cpu: "1000m"
      limits:
        memory: "9Gi"
        cpu: "7000m"

    cacheVolumeClaimTemplate:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "standard"
      resources:
        requests:
          storage: 1Gi

    image:
      repository: "andreykoltsov/pravega"
      pullPolicy: Always

    options:
      metrics.enableStatistics: "true"
      metrics.outputFrequencySeconds: "10"
      metrics.enableInfluxDBReporter: "true"
      metrics.influxDBURI: "<INFLUX DB URI>"
      metrics.influxDBName: "<InfluxDB target DB name>"
      metrics.influxDBRetention: "two_hour"

      controller.metrics.enableStatistics: "true"
      controller.metrics.outputFrequencySeconds: "10"
      controller.metrics.enableInfluxDBReporter: "true"
      controller.metrics.influxDBURI: "<INFLUX DB URI>"
      controller.metrics.influxDBName: "<InfluxDB target DB name>"
      controller.metrics.influxDBRetention: "two_hour"

      controller.containerCount: "32"
      controller.retention.bucketCount: "10"
      controller.service.asyncTaskPoolSize: "20"
      controller.retention.threadCount: "4"
      writer.flushThresholdBytes: "1048576"
      writer.maxFlushSizeBytes: "1048576"
      pravegaservice.containerCount: "32"
```

- *2. Manifest B*: updated property names, Segment Store exposes metrics just fine. Changed section has been marked with ` Start / End of changes`. Basically, I've changed all of the properties that're under `metrics.*` field:

```
apiVersion: "pravega.pravega.io/v1beta1"
kind: "PravegaCluster"
metadata:
  name: "pravega-cluster"
spec:
  version: "0.8.0-2568.efa9e08b2"
  zookeeperUri: zookeeper-client:2181
  bookkeeperUri: "bookkeeper-bookie-0.bookkeeper-bookie-headless.default.svc.cluster.local:3181"

  pravega:
    controllerReplicas: 1
    controllerResources:
      requests:
        memory: "3Gi"
        cpu: "500m"
      limits:
        memory: "5Gi"
        cpu: "3000m"

    segmentStoreReplicas: 1
    segmentStoreResources:
      requests:
        memory: "4Gi"
        cpu: "1000m"
      limits:
        memory: "9Gi"
        cpu: "7000m"

    cacheVolumeClaimTemplate:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "standard"
      resources:
        requests:
          storage: 1Gi

    image:
      repository: "andreykoltsov/pravega"
      pullPolicy: Always

    options:

      # -- Start of changes
      metrics.statistics.enable: "true"
      metrics.influxDB.reporter.enable: "true"
      metrics.influxDB.connect.uri: "<INFLUX DB URI>"
      metrics.influxDB.connect.db.name: "<InfluxDB target DB name>"
      metrics.influxDB.retention: "two_hour"
      metrics.output.frequency.seconds: "10"
      controller.metrics.statistics.enable: "true"
      controller.metrics.influxDB.reporter.enable: "true"
      controller.metrics.influxDB.connect.uri: <INFLUX DB URI>
      controller.metrics.influxDB.connect.db.name: "<InfluxDB target DB name>"
      controller.metrics.influxDB.retention: "two_hour"
      controller.metrics.output.frequency.seconds: "10"
      # -- End of changes

      controller.containerCount: "32"
      controller.retention.bucketCount: "10"
      controller.service.asyncTaskPoolSize: "20"
      controller.retention.threadCount: "4"
      writer.flushThresholdBytes: "1048576"
      writer.maxFlushSizeBytes: "1048576"
      pravegaservice.containerCount: "32"
```

**Problem location**
I assume `Segment Store Service`

**Suggestions for an improvement**
None
