### ISSUE TITLE
Pravega Installation on Kubernetes Update

### ISSUE THREAD

**Issue by dellThejas** [pravega/pravega#5585]
**Problem description**
The Pravega Installation guide on Kubernetes is outdated. 

**Problem location**
Pravega docs > Running Pravega > Deploying in Kubernetes

**Suggestions for an improvement**
Following are the updates for each sections:
- Requirements:
1. Kubernetes 1.15+ required
2. An existing Apache Zookeeper 3.6.1 cluster
3. Bookkeeper setup using  [bookkeeper-operator](https://github.com/pravega/bookkeeper-operator)

Deploy a sample Pravega cluster

1. Modify the `pravega.yaml`

```
apiVersion: "pravega.pravega.io/v1beta1"
kind: "PravegaCluster"
metadata:
  name: "pravega"
spec:
  version: 0.8.0
  zookeeperUri: [ZOOKEEPER_HOST]:2181
  bookkeeperUri: [BOOKKEEPER_SVC]:3181"
  pravega:
    controllerReplicas: 1
    segmentStoreReplicas: 3
    cacheVolumeClaimTemplate:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "standard"
      resources:
        requests:
          storage: 20Gi
    image:
      repository: pravega/pravega
    longtermStorage:
      filesystem:
        persistentVolumeClaim:
          claimName: pravega-tier2
```
 Add under: "[BOOKKEEPER_SVC] is the host or IP address of your Bookkeeper deployment"
